apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aboacp8kk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aboacp8kk-go 
  name: aboacp8kk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aboacp8kk-go 
